### ISSUE TITLE
Push notification not sent when creating from inside node

### ISSUE THREAD

**Issue by ghost** [jonathan-casarrubias/loopback-component-pubsub#10]
Hi, the component works fine if I create a new record from the REST API, but if I call for example `app.models.PushMessage.create({message: "wow"}, function(err, obj) {` from inside node.js, the record is created, but the push message is not. Is this an issue?

**Comment by jonathan-casarrubias** [comment]
Hello @Mc128k thanks for reporthing the issue, I will verify this issue asap..

Cheers!!
Jon

**Comment by jonathan-casarrubias** [comment]
I already verified and certainly does not work when calling from NodeJS.

Part of the mechanism is to run a remoteHook when each of the remotes are called, unfortunately this is not happening, though I remember it used to..

Anyway, I already tested with operation hook and these does not provide the endpoint name, thus it will need extra configuration by exposing the http context to know what is the current middelware route.

Not sure if it is a good idea to make the developers expose the context, but I think It would be possible to support both, just remoteHooks or by accepting enabling the context would be possible to use operationHooks and send the messages regardless you are using REST or NodeJS APIs.

This will need further research.

Cheers!
Jon

**Comment by ghost** [comment]
Ok.... then how do I send a notification to a client? It's not strictly necessary to create a record, I just need to pass a JSON object. Is it possible to directly call the push API?

Thanks

**Comment by jonathan-casarrubias** [comment]
Actually... That is something that I have closest in the scope, I expect to deliver a bidirectional interface that will allow custom messaging.

Please see this issue: https://github.com/mean-expert-official/loopback-sdk-builder/issues/112

I expect to deliver this functionality in the next couple of weeks.

Cheers,
Jon

**Comment by ghost** [comment]
Thanks a lot, i'll be the first to test it, as I'm building an app that relies on these types of messages. Basically I want to notify an app in a specific workstation that there is an incoming message, along with some details.

**Comment by jonathan-casarrubias** [comment]
NOTE

I have been researching a lot and due LoopBack limitations it is impossible to make the PubSub functionality to be executed from Node.

RemoteHooks that provides the RemoteMethod information are only called from Web Context: https://groups.google.com/forum/#!topic/loopbackjs/63wcGK8S_hQ

OperationHooks does not provide any remoting information which disables the possibility to publish to the right subscribed endpoints.
https://gist.github.com/bajtos/b8157112452eeaf984c9

I'm still adding the possibility to manually send messages from NodeJS to SDK Client, this will help mitigate this issue allowing developers to send messages from back to front end.

**Comment by jonathan-casarrubias** [comment]
This functionality has been implemented but not in this module.

This module is deprecated, use https://github.com/mean-expert-official/loopback-component-realtime instead.

DOCUMENTATION: https://github.com/mean-expert-official/loopback-sdk-builder/wiki/9.-(NEW)-IO-Module
