### ISSUE TITLE
Question: Object subscribing 

### ISSUE THREAD

**Issue by sirgalleto** [jonathan-casarrubias/loopback-component-pubsub#8]
There are other ways to filter subscription with a when or any filter like that?

**Comment by jonathan-casarrubias** [comment]
It is not yet documented, but the functionality is there and it's well explained in the following link:

http://mean.expert/2016/06/27/angular-2-ultimate-real-time-part-3/#Include-Messages-Account

**Comment by sirgalleto** [comment]
So, if I change the pub/sub logic and I have user - notifications. How subscribe to specific user notifications?

**Comment by sirgalleto** [comment]
The notification have userId obviosly, but I dont find the match to subscriber.

**Comment by sirgalleto** [comment]
Ok, I understand.

When I create the user relation with your notification, I use the PubSub mixin and create the sdk, then in the SDK I use user.onCreateNotification(userId) to subscribe only the user (as a channel) notification?

**Comment by jonathan-casarrubias** [comment]
Yes if you create a notification model and then create a relationship with the user, you will get new methods when creating the SDK, these will allow you to subscribe to specific events,

the one you mention, will fire an event everytime the user with the given Id creates a new notification
